### ISSUE TITLE
Magnet Piston breaking

### ISSUE THREAD

**Issue by CosmicjLightning** [crazysnailboy/MagnetPistons#1]
When you build a magnet piston in a block swapper, it will either break the magnet piston facing down or the magnet piston facing on the side. also once you do it for a few times than they just flat out stop working, even when placing new ones.

**Comment by crazysnailboy** [comment]
Do you have a video or a map which demonstrates this?

**Comment by CosmicjLightning** [comment]
K I tried for a good 20 min to replicate it and couldn't at which than realized I removed the weather mod and it's dependent from my mods. So the mod culprit is weathers, tornadoes, and stuff mod on curseforge. A good weather mod gone bad and owner don't care to fix it(whitelisting and blacklisting never worked on it)....It even conflicts with astral sorcery. So this issue is fixed and sorry to have bothered you.

**Comment by crazysnailboy** [comment]
No problem :) Glad you figured out what was causing it (and glad it wasn't this mod!)
